export { default as FirstPage } from './FirstPage'
// export { default as Join } from './Join'
export { default as Login } from './Login'
export { default as Mainpage } from './Mainpage'
export { default as Mypage } from './Mypage'
// export { default as Page } from './Page'
export { default as Signup } from './Signup'
// export { default as FirstPage } from './FirstPage'
